# Generated by Django 4.1.3 on 2024-04-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_events_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='category_description',
            field=models.TextField(max_length=800),
        ),
    ]
